// Code generated by MockGen. DO NOT EDIT.
// Source: worker.go
//
// Generated by this command:
//
//	mockgen -source=worker.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "problum/internal/attempt/service/dto"
	service "problum/internal/problem/service"
	dto0 "problum/internal/problem/service/dto"
	dto1 "problum/internal/solver/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAttemptService is a mock of AttemptService interface.
type MockAttemptService struct {
	ctrl     *gomock.Controller
	recorder *MockAttemptServiceMockRecorder
	isgomock struct{}
}

// MockAttemptServiceMockRecorder is the mock recorder for MockAttemptService.
type MockAttemptServiceMockRecorder struct {
	mock *MockAttemptService
}

// NewMockAttemptService creates a new mock instance.
func NewMockAttemptService(ctrl *gomock.Controller) *MockAttemptService {
	mock := &MockAttemptService{ctrl: ctrl}
	mock.recorder = &MockAttemptServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttemptService) EXPECT() *MockAttemptServiceMockRecorder {
	return m.recorder
}

// Submit mocks base method.
func (m *MockAttemptService) Submit(arg0 context.Context, arg1 *dto.Attempt) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockAttemptServiceMockRecorder) Submit(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockAttemptService)(nil).Submit), arg0, arg1)
}

// Update mocks base method.
func (m *MockAttemptService) Update(ctx context.Context, attempt *dto.Attempt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, attempt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAttemptServiceMockRecorder) Update(ctx, attempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAttemptService)(nil).Update), ctx, attempt)
}

// MockSolver is a mock of Solver interface.
type MockSolver struct {
	ctrl     *gomock.Controller
	recorder *MockSolverMockRecorder
	isgomock struct{}
}

// MockSolverMockRecorder is the mock recorder for MockSolver.
type MockSolverMockRecorder struct {
	mock *MockSolver
}

// NewMockSolver creates a new mock instance.
func NewMockSolver(ctrl *gomock.Controller) *MockSolver {
	mock := &MockSolver{ctrl: ctrl}
	mock.recorder = &MockSolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSolver) EXPECT() *MockSolverMockRecorder {
	return m.recorder
}

// Solve mocks base method.
func (m *MockSolver) Solve(arg0 context.Context, arg1 *dto.Attempt) (*dto1.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Solve", arg0, arg1)
	ret0, _ := ret[0].(*dto1.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Solve indicates an expected call of Solve.
func (mr *MockSolverMockRecorder) Solve(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Solve", reflect.TypeOf((*MockSolver)(nil).Solve), arg0, arg1)
}

// MockProblemService is a mock of ProblemService interface.
type MockProblemService struct {
	ctrl     *gomock.Controller
	recorder *MockProblemServiceMockRecorder
	isgomock struct{}
}

// MockProblemServiceMockRecorder is the mock recorder for MockProblemService.
type MockProblemServiceMockRecorder struct {
	mock *MockProblemService
}

// NewMockProblemService creates a new mock instance.
func NewMockProblemService(ctrl *gomock.Controller) *MockProblemService {
	mock := &MockProblemService{ctrl: ctrl}
	mock.recorder = &MockProblemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProblemService) EXPECT() *MockProblemServiceMockRecorder {
	return m.recorder
}

// GetWithOptions mocks base method.
func (m *MockProblemService) GetWithOptions(arg0 context.Context, arg1 int, arg2 ...service.Option) (*dto0.Problem, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWithOptions", varargs...)
	ret0, _ := ret[0].(*dto0.Problem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithOptions indicates an expected call of GetWithOptions.
func (mr *MockProblemServiceMockRecorder) GetWithOptions(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithOptions", reflect.TypeOf((*MockProblemService)(nil).GetWithOptions), varargs...)
}
