// Code generated by MockGen. DO NOT EDIT.
// Source: solver.go
//
// Generated by this command:
//
//	mockgen -source=solver.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	service "problum/internal/problem/service"
	dto "problum/internal/problem/service/dto"
	dto0 "problum/internal/template/service/dto"
	dto1 "problum/internal/test/service/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTestService is a mock of TestService interface.
type MockTestService struct {
	ctrl     *gomock.Controller
	recorder *MockTestServiceMockRecorder
	isgomock struct{}
}

// MockTestServiceMockRecorder is the mock recorder for MockTestService.
type MockTestServiceMockRecorder struct {
	mock *MockTestService
}

// NewMockTestService creates a new mock instance.
func NewMockTestService(ctrl *gomock.Controller) *MockTestService {
	mock := &MockTestService{ctrl: ctrl}
	mock.recorder = &MockTestServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestService) EXPECT() *MockTestServiceMockRecorder {
	return m.recorder
}

// GetByProblemID mocks base method.
func (m *MockTestService) GetByProblemID(arg0 context.Context, arg1 int) (*dto1.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProblemID", arg0, arg1)
	ret0, _ := ret[0].(*dto1.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProblemID indicates an expected call of GetByProblemID.
func (mr *MockTestServiceMockRecorder) GetByProblemID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProblemID", reflect.TypeOf((*MockTestService)(nil).GetByProblemID), arg0, arg1)
}

// MockTemplateService is a mock of TemplateService interface.
type MockTemplateService struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateServiceMockRecorder
	isgomock struct{}
}

// MockTemplateServiceMockRecorder is the mock recorder for MockTemplateService.
type MockTemplateServiceMockRecorder struct {
	mock *MockTemplateService
}

// NewMockTemplateService creates a new mock instance.
func NewMockTemplateService(ctrl *gomock.Controller) *MockTemplateService {
	mock := &MockTemplateService{ctrl: ctrl}
	mock.recorder = &MockTemplateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateService) EXPECT() *MockTemplateServiceMockRecorder {
	return m.recorder
}

// GetByProblemIDAndLanguage mocks base method.
func (m *MockTemplateService) GetByProblemIDAndLanguage(arg0 context.Context, arg1 int, arg2 string) (*dto0.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProblemIDAndLanguage", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto0.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProblemIDAndLanguage indicates an expected call of GetByProblemIDAndLanguage.
func (mr *MockTemplateServiceMockRecorder) GetByProblemIDAndLanguage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProblemIDAndLanguage", reflect.TypeOf((*MockTemplateService)(nil).GetByProblemIDAndLanguage), arg0, arg1, arg2)
}

// MockProblemService is a mock of ProblemService interface.
type MockProblemService struct {
	ctrl     *gomock.Controller
	recorder *MockProblemServiceMockRecorder
	isgomock struct{}
}

// MockProblemServiceMockRecorder is the mock recorder for MockProblemService.
type MockProblemServiceMockRecorder struct {
	mock *MockProblemService
}

// NewMockProblemService creates a new mock instance.
func NewMockProblemService(ctrl *gomock.Controller) *MockProblemService {
	mock := &MockProblemService{ctrl: ctrl}
	mock.recorder = &MockProblemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProblemService) EXPECT() *MockProblemServiceMockRecorder {
	return m.recorder
}

// GetWithOptions mocks base method.
func (m *MockProblemService) GetWithOptions(arg0 context.Context, arg1 int, arg2 ...service.Option) (*dto.Problem, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWithOptions", varargs...)
	ret0, _ := ret[0].(*dto.Problem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithOptions indicates an expected call of GetWithOptions.
func (mr *MockProblemServiceMockRecorder) GetWithOptions(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithOptions", reflect.TypeOf((*MockProblemService)(nil).GetWithOptions), varargs...)
}
