// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "problum/internal/attempt/service/dto"
	model "problum/internal/model"
	dto0 "problum/internal/template/service/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRepository) Get(arg0 context.Context, arg1 int) (*model.Problem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*model.Problem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), arg0, arg1)
}

// ListByLessonID mocks base method.
func (m *MockRepository) ListByLessonID(arg0 context.Context, arg1 int) ([]*model.Problem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByLessonID", arg0, arg1)
	ret0, _ := ret[0].([]*model.Problem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByLessonID indicates an expected call of ListByLessonID.
func (mr *MockRepositoryMockRecorder) ListByLessonID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByLessonID", reflect.TypeOf((*MockRepository)(nil).ListByLessonID), arg0, arg1)
}

// MockAttemptService is a mock of AttemptService interface.
type MockAttemptService struct {
	ctrl     *gomock.Controller
	recorder *MockAttemptServiceMockRecorder
	isgomock struct{}
}

// MockAttemptServiceMockRecorder is the mock recorder for MockAttemptService.
type MockAttemptServiceMockRecorder struct {
	mock *MockAttemptService
}

// NewMockAttemptService creates a new mock instance.
func NewMockAttemptService(ctrl *gomock.Controller) *MockAttemptService {
	mock := &MockAttemptService{ctrl: ctrl}
	mock.recorder = &MockAttemptServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttemptService) EXPECT() *MockAttemptServiceMockRecorder {
	return m.recorder
}

// Submit mocks base method.
func (m *MockAttemptService) Submit(arg0 context.Context, arg1 *dto.Attempt) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockAttemptServiceMockRecorder) Submit(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockAttemptService)(nil).Submit), arg0, arg1)
}

// MockTemplateService is a mock of TemplateService interface.
type MockTemplateService struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateServiceMockRecorder
	isgomock struct{}
}

// MockTemplateServiceMockRecorder is the mock recorder for MockTemplateService.
type MockTemplateServiceMockRecorder struct {
	mock *MockTemplateService
}

// NewMockTemplateService creates a new mock instance.
func NewMockTemplateService(ctrl *gomock.Controller) *MockTemplateService {
	mock := &MockTemplateService{ctrl: ctrl}
	mock.recorder = &MockTemplateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateService) EXPECT() *MockTemplateServiceMockRecorder {
	return m.recorder
}

// GetByProblemIDAndLanguage mocks base method.
func (m *MockTemplateService) GetByProblemIDAndLanguage(arg0 context.Context, arg1 int, arg2 string) (*dto0.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProblemIDAndLanguage", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto0.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProblemIDAndLanguage indicates an expected call of GetByProblemIDAndLanguage.
func (mr *MockTemplateServiceMockRecorder) GetByProblemIDAndLanguage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProblemIDAndLanguage", reflect.TypeOf((*MockTemplateService)(nil).GetByProblemIDAndLanguage), arg0, arg1, arg2)
}

// GetLanguagesByProblemID mocks base method.
func (m *MockTemplateService) GetLanguagesByProblemID(arg0 context.Context, arg1 int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLanguagesByProblemID", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLanguagesByProblemID indicates an expected call of GetLanguagesByProblemID.
func (mr *MockTemplateServiceMockRecorder) GetLanguagesByProblemID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLanguagesByProblemID", reflect.TypeOf((*MockTemplateService)(nil).GetLanguagesByProblemID), arg0, arg1)
}
