// Code generated by MockGen. DO NOT EDIT.
// Source: problum/internal/api (interfaces: AttemptAPI,AuthAPI,CourseAPI,EnrollmentAPI,LessonAPI,ProblemAPI)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service.go -package=mocks problum/internal/api AttemptAPI,AuthAPI,CourseAPI,EnrollmentAPI,LessonAPI,ProblemAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	fiber "github.com/gofiber/fiber/v3"
	gomock "go.uber.org/mock/gomock"
)

// MockAttemptAPI is a mock of AttemptAPI interface.
type MockAttemptAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAttemptAPIMockRecorder
	isgomock struct{}
}

// MockAttemptAPIMockRecorder is the mock recorder for MockAttemptAPI.
type MockAttemptAPIMockRecorder struct {
	mock *MockAttemptAPI
}

// NewMockAttemptAPI creates a new mock instance.
func NewMockAttemptAPI(ctrl *gomock.Controller) *MockAttemptAPI {
	mock := &MockAttemptAPI{ctrl: ctrl}
	mock.recorder = &MockAttemptAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttemptAPI) EXPECT() *MockAttemptAPIMockRecorder {
	return m.recorder
}

// ListByProblemID mocks base method.
func (m *MockAttemptAPI) ListByProblemID(arg0 fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProblemID", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListByProblemID indicates an expected call of ListByProblemID.
func (mr *MockAttemptAPIMockRecorder) ListByProblemID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProblemID", reflect.TypeOf((*MockAttemptAPI)(nil).ListByProblemID), arg0)
}

// ListByUserID mocks base method.
func (m *MockAttemptAPI) ListByUserID(arg0 fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockAttemptAPIMockRecorder) ListByUserID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockAttemptAPI)(nil).ListByUserID), arg0)
}

// MockAuthAPI is a mock of AuthAPI interface.
type MockAuthAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAuthAPIMockRecorder
	isgomock struct{}
}

// MockAuthAPIMockRecorder is the mock recorder for MockAuthAPI.
type MockAuthAPIMockRecorder struct {
	mock *MockAuthAPI
}

// NewMockAuthAPI creates a new mock instance.
func NewMockAuthAPI(ctrl *gomock.Controller) *MockAuthAPI {
	mock := &MockAuthAPI{ctrl: ctrl}
	mock.recorder = &MockAuthAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthAPI) EXPECT() *MockAuthAPIMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthAPI) Login(arg0 fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockAuthAPIMockRecorder) Login(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthAPI)(nil).Login), arg0)
}

// Logout mocks base method.
func (m *MockAuthAPI) Logout(arg0 fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthAPIMockRecorder) Logout(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthAPI)(nil).Logout), arg0)
}

// Refresh mocks base method.
func (m *MockAuthAPI) Refresh(arg0 fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthAPIMockRecorder) Refresh(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuthAPI)(nil).Refresh), arg0)
}

// Register mocks base method.
func (m *MockAuthAPI) Register(arg0 fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockAuthAPIMockRecorder) Register(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthAPI)(nil).Register), arg0)
}

// MockCourseAPI is a mock of CourseAPI interface.
type MockCourseAPI struct {
	ctrl     *gomock.Controller
	recorder *MockCourseAPIMockRecorder
	isgomock struct{}
}

// MockCourseAPIMockRecorder is the mock recorder for MockCourseAPI.
type MockCourseAPIMockRecorder struct {
	mock *MockCourseAPI
}

// NewMockCourseAPI creates a new mock instance.
func NewMockCourseAPI(ctrl *gomock.Controller) *MockCourseAPI {
	mock := &MockCourseAPI{ctrl: ctrl}
	mock.recorder = &MockCourseAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourseAPI) EXPECT() *MockCourseAPIMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCourseAPI) Get(arg0 fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockCourseAPIMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCourseAPI)(nil).Get), arg0)
}

// List mocks base method.
func (m *MockCourseAPI) List(arg0 fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockCourseAPIMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCourseAPI)(nil).List), arg0)
}

// MockEnrollmentAPI is a mock of EnrollmentAPI interface.
type MockEnrollmentAPI struct {
	ctrl     *gomock.Controller
	recorder *MockEnrollmentAPIMockRecorder
	isgomock struct{}
}

// MockEnrollmentAPIMockRecorder is the mock recorder for MockEnrollmentAPI.
type MockEnrollmentAPIMockRecorder struct {
	mock *MockEnrollmentAPI
}

// NewMockEnrollmentAPI creates a new mock instance.
func NewMockEnrollmentAPI(ctrl *gomock.Controller) *MockEnrollmentAPI {
	mock := &MockEnrollmentAPI{ctrl: ctrl}
	mock.recorder = &MockEnrollmentAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrollmentAPI) EXPECT() *MockEnrollmentAPIMockRecorder {
	return m.recorder
}

// Enroll mocks base method.
func (m *MockEnrollmentAPI) Enroll(arg0 fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enroll", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enroll indicates an expected call of Enroll.
func (mr *MockEnrollmentAPIMockRecorder) Enroll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enroll", reflect.TypeOf((*MockEnrollmentAPI)(nil).Enroll), arg0)
}

// MockLessonAPI is a mock of LessonAPI interface.
type MockLessonAPI struct {
	ctrl     *gomock.Controller
	recorder *MockLessonAPIMockRecorder
	isgomock struct{}
}

// MockLessonAPIMockRecorder is the mock recorder for MockLessonAPI.
type MockLessonAPIMockRecorder struct {
	mock *MockLessonAPI
}

// NewMockLessonAPI creates a new mock instance.
func NewMockLessonAPI(ctrl *gomock.Controller) *MockLessonAPI {
	mock := &MockLessonAPI{ctrl: ctrl}
	mock.recorder = &MockLessonAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLessonAPI) EXPECT() *MockLessonAPIMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockLessonAPI) Get(arg0 fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockLessonAPIMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLessonAPI)(nil).Get), arg0)
}

// MockProblemAPI is a mock of ProblemAPI interface.
type MockProblemAPI struct {
	ctrl     *gomock.Controller
	recorder *MockProblemAPIMockRecorder
	isgomock struct{}
}

// MockProblemAPIMockRecorder is the mock recorder for MockProblemAPI.
type MockProblemAPIMockRecorder struct {
	mock *MockProblemAPI
}

// NewMockProblemAPI creates a new mock instance.
func NewMockProblemAPI(ctrl *gomock.Controller) *MockProblemAPI {
	mock := &MockProblemAPI{ctrl: ctrl}
	mock.recorder = &MockProblemAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProblemAPI) EXPECT() *MockProblemAPIMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockProblemAPI) Get(arg0 fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockProblemAPIMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProblemAPI)(nil).Get), arg0)
}

// Submit mocks base method.
func (m *MockProblemAPI) Submit(arg0 fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Submit indicates an expected call of Submit.
func (mr *MockProblemAPIMockRecorder) Submit(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockProblemAPI)(nil).Submit), arg0)
}
