// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "problum/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetByProblemID mocks base method.
func (m *MockRepository) GetByProblemID(ctx context.Context, problemID int) (*model.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProblemID", ctx, problemID)
	ret0, _ := ret[0].(*model.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProblemID indicates an expected call of GetByProblemID.
func (mr *MockRepositoryMockRecorder) GetByProblemID(ctx, problemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProblemID", reflect.TypeOf((*MockRepository)(nil).GetByProblemID), ctx, problemID)
}
