// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "problum/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetByProblemIDAndLanguage mocks base method.
func (m *MockRepository) GetByProblemIDAndLanguage(arg0 context.Context, arg1 int, arg2 string) (*model.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProblemIDAndLanguage", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProblemIDAndLanguage indicates an expected call of GetByProblemIDAndLanguage.
func (mr *MockRepositoryMockRecorder) GetByProblemIDAndLanguage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProblemIDAndLanguage", reflect.TypeOf((*MockRepository)(nil).GetByProblemIDAndLanguage), arg0, arg1, arg2)
}

// GetLanguagesByProblemID mocks base method.
func (m *MockRepository) GetLanguagesByProblemID(arg0 context.Context, arg1 int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLanguagesByProblemID", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLanguagesByProblemID indicates an expected call of GetLanguagesByProblemID.
func (mr *MockRepositoryMockRecorder) GetLanguagesByProblemID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLanguagesByProblemID", reflect.TypeOf((*MockRepository)(nil).GetLanguagesByProblemID), arg0, arg1)
}
