// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "problum/internal/enrollment/service/dto"
	dto0 "problum/internal/lesson/service/dto"
	model "problum/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRepository) Get(arg0 context.Context, arg1 int) (*model.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*model.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockRepository) List(arg0 context.Context) ([]*model.Course, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]*model.Course)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), arg0)
}

// MockLessonService is a mock of LessonService interface.
type MockLessonService struct {
	ctrl     *gomock.Controller
	recorder *MockLessonServiceMockRecorder
	isgomock struct{}
}

// MockLessonServiceMockRecorder is the mock recorder for MockLessonService.
type MockLessonServiceMockRecorder struct {
	mock *MockLessonService
}

// NewMockLessonService creates a new mock instance.
func NewMockLessonService(ctrl *gomock.Controller) *MockLessonService {
	mock := &MockLessonService{ctrl: ctrl}
	mock.recorder = &MockLessonServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLessonService) EXPECT() *MockLessonServiceMockRecorder {
	return m.recorder
}

// ListByCourseID mocks base method.
func (m *MockLessonService) ListByCourseID(ctx context.Context, id int) ([]*dto0.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCourseID", ctx, id)
	ret0, _ := ret[0].([]*dto0.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCourseID indicates an expected call of ListByCourseID.
func (mr *MockLessonServiceMockRecorder) ListByCourseID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCourseID", reflect.TypeOf((*MockLessonService)(nil).ListByCourseID), ctx, id)
}

// MockEnrollmentService is a mock of EnrollmentService interface.
type MockEnrollmentService struct {
	ctrl     *gomock.Controller
	recorder *MockEnrollmentServiceMockRecorder
	isgomock struct{}
}

// MockEnrollmentServiceMockRecorder is the mock recorder for MockEnrollmentService.
type MockEnrollmentServiceMockRecorder struct {
	mock *MockEnrollmentService
}

// NewMockEnrollmentService creates a new mock instance.
func NewMockEnrollmentService(ctrl *gomock.Controller) *MockEnrollmentService {
	mock := &MockEnrollmentService{ctrl: ctrl}
	mock.recorder = &MockEnrollmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrollmentService) EXPECT() *MockEnrollmentServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockEnrollmentService) Get(arg0 context.Context, arg1, arg2 int) (*dto.Enrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.Enrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEnrollmentServiceMockRecorder) Get(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEnrollmentService)(nil).Get), arg0, arg1, arg2)
}

// GetListByUserID mocks base method.
func (m *MockEnrollmentService) GetListByUserID(arg0 context.Context, arg1 int) ([]*dto.Enrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListByUserID", arg0, arg1)
	ret0, _ := ret[0].([]*dto.Enrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListByUserID indicates an expected call of GetListByUserID.
func (mr *MockEnrollmentServiceMockRecorder) GetListByUserID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListByUserID", reflect.TypeOf((*MockEnrollmentService)(nil).GetListByUserID), arg0, arg1)
}
