// Code generated by MockGen. DO NOT EDIT.
// Source: problum/internal/middleware (interfaces: AttemptService,EnrollmentService,LessonService,ProblemService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service.go -package=mocks problum/internal/middleware AttemptService,EnrollmentService,LessonService,ProblemService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "problum/internal/attempt/service/dto"
	dto0 "problum/internal/enrollment/service/dto"
	dto1 "problum/internal/lesson/service/dto"
	service "problum/internal/problem/service"
	dto2 "problum/internal/problem/service/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAttemptService is a mock of AttemptService interface.
type MockAttemptService struct {
	ctrl     *gomock.Controller
	recorder *MockAttemptServiceMockRecorder
	isgomock struct{}
}

// MockAttemptServiceMockRecorder is the mock recorder for MockAttemptService.
type MockAttemptServiceMockRecorder struct {
	mock *MockAttemptService
}

// NewMockAttemptService creates a new mock instance.
func NewMockAttemptService(ctrl *gomock.Controller) *MockAttemptService {
	mock := &MockAttemptService{ctrl: ctrl}
	mock.recorder = &MockAttemptServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttemptService) EXPECT() *MockAttemptServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAttemptService) Get(arg0 context.Context, arg1 int) (*dto.Attempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*dto.Attempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAttemptServiceMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAttemptService)(nil).Get), arg0, arg1)
}

// MockEnrollmentService is a mock of EnrollmentService interface.
type MockEnrollmentService struct {
	ctrl     *gomock.Controller
	recorder *MockEnrollmentServiceMockRecorder
	isgomock struct{}
}

// MockEnrollmentServiceMockRecorder is the mock recorder for MockEnrollmentService.
type MockEnrollmentServiceMockRecorder struct {
	mock *MockEnrollmentService
}

// NewMockEnrollmentService creates a new mock instance.
func NewMockEnrollmentService(ctrl *gomock.Controller) *MockEnrollmentService {
	mock := &MockEnrollmentService{ctrl: ctrl}
	mock.recorder = &MockEnrollmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrollmentService) EXPECT() *MockEnrollmentServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockEnrollmentService) Get(ctx context.Context, courseID, userID int) (*dto0.Enrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, courseID, userID)
	ret0, _ := ret[0].(*dto0.Enrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEnrollmentServiceMockRecorder) Get(ctx, courseID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEnrollmentService)(nil).Get), ctx, courseID, userID)
}

// MockLessonService is a mock of LessonService interface.
type MockLessonService struct {
	ctrl     *gomock.Controller
	recorder *MockLessonServiceMockRecorder
	isgomock struct{}
}

// MockLessonServiceMockRecorder is the mock recorder for MockLessonService.
type MockLessonServiceMockRecorder struct {
	mock *MockLessonService
}

// NewMockLessonService creates a new mock instance.
func NewMockLessonService(ctrl *gomock.Controller) *MockLessonService {
	mock := &MockLessonService{ctrl: ctrl}
	mock.recorder = &MockLessonServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLessonService) EXPECT() *MockLessonServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockLessonService) Get(ctx context.Context, id int) (*dto1.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*dto1.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLessonServiceMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLessonService)(nil).Get), ctx, id)
}

// MockProblemService is a mock of ProblemService interface.
type MockProblemService struct {
	ctrl     *gomock.Controller
	recorder *MockProblemServiceMockRecorder
	isgomock struct{}
}

// MockProblemServiceMockRecorder is the mock recorder for MockProblemService.
type MockProblemServiceMockRecorder struct {
	mock *MockProblemService
}

// NewMockProblemService creates a new mock instance.
func NewMockProblemService(ctrl *gomock.Controller) *MockProblemService {
	mock := &MockProblemService{ctrl: ctrl}
	mock.recorder = &MockProblemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProblemService) EXPECT() *MockProblemServiceMockRecorder {
	return m.recorder
}

// GetWithOptions mocks base method.
func (m *MockProblemService) GetWithOptions(arg0 context.Context, arg1 int, arg2 ...service.Option) (*dto2.Problem, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetWithOptions", varargs...)
	ret0, _ := ret[0].(*dto2.Problem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithOptions indicates an expected call of GetWithOptions.
func (mr *MockProblemServiceMockRecorder) GetWithOptions(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithOptions", reflect.TypeOf((*MockProblemService)(nil).GetWithOptions), varargs...)
}
